[package]
name = "geoelan"
version = "2.0.0"
edition = "2021"
# doc = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4", features = ["wrap_help"]}
time = "0.3"
geojson = {version = "0.24", features = ["geo-types"]}
serde_json = "1.0.79"
kml = "0.5"
walkdir = "2"
rand = "0.8.5"
regex = "1"
fit-rs = {path="../lib/fit-rs"}
gpmf-rs = {path="../lib/gpmf-rs"}
eaf-rs = {path="../lib/eaf-rs"}
mp4iter = {path="../lib/mp4iter"}
jpegiter = {path="../lib/jpegiter"}
